// packages/codegen-react/src/vue-plugin.ts
import type { UIHFile, LayoutBlock, MotionBlock, LogicBlock, StateBlock, DataBlock, Node } from "uih-parser";
import prettier from "prettier";
import type { CodegenPlugin } from "./plugin.js";

/**
 * Vue 3 code generation plugin with Composition API
 */
export class VuePlugin implements CodegenPlugin {
  readonly name = "vue";
  readonly fileExtension = ".vue";

  async generate(file: UIHFile): Promise<string> {
    // Generate user imports from .uih files and collect imported component names
    const importedComponents = new Set<string>();
    const userImports = file.imports.map((imp) => {
      // Track all imported component names
      imp.names.forEach(name => importedComponents.add(name));

      const importPath = imp.from.replace(/\.uih$/, "");
      if (imp.names.length === 1) {
        return `import ${imp.names[0]} from "${importPath}";`;
      } else {
        return `import { ${imp.names.join(", ")} } from "${importPath}";`;
      }
    }).join("\n");

    const layout = file.blocks.find((b) => b.type === "Layout") as
      | LayoutBlock
      | undefined;
    if (!layout) throw new Error("Layout block required");

    const motion = file.blocks.find((b) => b.type === "Motion") as
      | MotionBlock
      | undefined;

    const logic = file.blocks.find((b) => b.type === "Logic") as
      | LogicBlock
      | undefined;

    const state = file.blocks.find((b) => b.type === "State") as
      | StateBlock
      | undefined;

    const data = file.blocks.find((b) => b.type === "Data") as
      | DataBlock
      | undefined;

    const template = layout.nodes.map((n) => this.emitNode(n, 0, importedComponents)).join("\n");
    const motionStyles = motion ? this.generateMotionStyles(motion) : "";
    const { stateRefs, stateImports } = state ? this.generateStateRefs(state) : { stateRefs: "", stateImports: new Set<string>() };
    const { dataFetches, dataImports } = data ? this.generateDataFetches(data) : { dataFetches: "", dataImports: new Set<string>() };
    const { handlers, handlerImports } = logic ? this.generateLogicHandlers(logic) : { handlers: "", handlerImports: new Set<string>() };

    // Merge all imports
    const imports = new Set<string>();
    stateImports.forEach(imp => imports.add(imp));
    dataImports.forEach(imp => imports.add(imp));
    handlerImports.forEach(imp => imports.add(imp));

    const importStr = imports.size > 0 ? `import { ${[...imports].join(", ")} } from "vue";\n` : "";

    const code = `<template>
  <div class="container mx-auto p-6">
    ${template}
  </div>
</template>

<script setup lang="ts">
${userImports ? userImports + "\n" : ""}${importStr}${stateRefs}${dataFetches}${handlers}
</script>

${motionStyles ? `<style scoped>\n${motionStyles}\n</style>` : ""}
`;

    // Format with prettier (Vue parser)
    const formatted = await prettier.format(code.trim(), {
      parser: "vue",
      semi: true,
      singleQuote: false,
      trailingComma: "es5",
      printWidth: 80,
    });

    return formatted;
  }

  private emitNode(n: Node, indent: number = 0, importedComponents: Set<string>): string {
    const indentStr = "  ".repeat(indent);

    if (n.kind === "Text") {
      return `${indentStr}${n.text}`;
    }

    if (n.kind === "Conditional") {
      const thenJsx = n.thenNodes
        .map((node) => this.emitNode(node, indent + 1, importedComponents))
        .join("\n");

      if (n.elseNodes && n.elseNodes.length > 0) {
        const elseJsx = n.elseNodes
          .map((node) => this.emitNode(node, indent + 1, importedComponents))
          .join("\n");

        // Use template tag for multi-node conditionals
        if (n.thenNodes.length > 1 || n.elseNodes.length > 1) {
          return `${indentStr}<template v-if="${n.condition}">
${thenJsx}
${indentStr}</template>
${indentStr}<template v-else>
${elseJsx}
${indentStr}</template>`;
        } else {
          // Single nodes can use v-if/v-else directly
          return `${thenJsx.replace(/<(\w+)/, `<$1 v-if="${n.condition}"`)}
${elseJsx.replace(/<(\w+)/, `<$1 v-else`)}`;
        }
      }

      // No else branch
      if (n.thenNodes.length === 1) {
        return thenJsx.replace(/<(\w+)/, `<$1 v-if="${n.condition}"`);
      } else {
        return `${indentStr}<template v-if="${n.condition}">
${thenJsx}
${indentStr}</template>`;
      }
    }

    if (n.kind === "Loop") {
      const childrenJsx = n.children
        .map((node) => this.emitNode(node, indent + 1, importedComponents))
        .join("\n");

      // Use template tag for loops
      if (n.children.length > 1) {
        return `${indentStr}<template v-for="${n.iteratorVar} in ${n.iterableExpr}" :key="${n.iteratorVar}.id || Math.random()">
${childrenJsx}
${indentStr}</template>`;
      } else {
        // Single child can use v-for directly
        return childrenJsx.replace(
          /<(\w+)/,
          `<$1 v-for="${n.iteratorVar} in ${n.iterableExpr}" :key="${n.iteratorVar}.id || Math.random()"`
        );
      }
    }

    // Element node - check if it's an imported component first
    const componentName = n.name || "div";
    const vueComponent = importedComponents.has(componentName)
      ? componentName // Use imported component as-is
      : this.mapToVueComponent(componentName); // Map to HTML element

    const props = (n.props || [])
      .map((p) => {
        const value = String(p.value);
        // Check if value is a variable reference (starts with {)
        if (value.startsWith("{")) {
          return `:${p.key}="${value.slice(1, -1)}"`;
        }
        // Check if value is a number
        if (!isNaN(Number(value))) {
          return `:${p.key}="${value}"`;
        }
        // String literal
        return `${p.key}="${value}"`;
      })
      .join(" ");
    const children = (n.children || [])
      .map((c) => this.emitNode(c, indent + 1, importedComponents))
      .join("\n");

    if (children) {
      return `${indentStr}<${vueComponent} ${props}>
${children}
${indentStr}</${vueComponent}>`;
    } else {
      return `${indentStr}<${vueComponent} ${props} />`;
    }
  }

  private mapToVueComponent(name: string): string {
    // Map component names to Vue equivalents
    const mapping: Record<string, string> = {
      Button: "button",
      Input: "input",
      Card: "div",
      Badge: "span",
      Text: "p",
      Textarea: "textarea",
      Select: "select",
      SelectItem: "option",
      Checkbox: "input",
      Label: "label",
      Avatar: "div",
      Dialog: "div",
      Tooltip: "div",
      Switch: "input",
      Separator: "hr",
      Alert: "div",
      Progress: "progress",
      Skeleton: "div",
    };

    return mapping[name] || "div";
  }

  private generateMotionStyles(motion: MotionBlock): string {
    const cssRules = motion.rules.map((rule) => {
      const { selector, event, props } = rule;

      const cssProps: string[] = [];
      const transitions: string[] = [];

      Object.entries(props).forEach(([key, value]) => {
        if (key === "duration") {
          transitions.push(`all ${value}`);
        } else if (key === "scale") {
          cssProps.push(`transform: scale(${value});`);
        } else if (key === "opacity") {
          cssProps.push(`opacity: ${value};`);
        } else if (key === "rotate") {
          cssProps.push(`transform: rotate(${value}deg);`);
        } else if (key === "x") {
          cssProps.push(`transform: translateX(${value}px);`);
        } else if (key === "y") {
          cssProps.push(`transform: translateY(${value}px);`);
        }
      });

      if (transitions.length === 0) {
        transitions.push("all 200ms ease");
      }
      cssProps.push(`transition: ${transitions.join(", ")};`);

      let pseudo = "";
      if (event === "hover") pseudo = ":hover";
      else if (event === "focus") pseudo = ":focus";
      else if (event === "active") pseudo = ":active";

      return `${selector}${pseudo} {\n  ${cssProps.join("\n  ")}\n}`;
    });

    return cssRules.join("\n\n");
  }

  private generateStateRefs(state: StateBlock): { stateRefs: string; stateImports: Set<string> } {
    const imports = new Set<string>();
    imports.add("ref");

    const refs = state.declarations.map((decl) => {
      let initialValue: string;
      if (typeof decl.initialValue === "string") {
        initialValue = `"${decl.initialValue}"`;
      } else if (typeof decl.initialValue === "boolean") {
        initialValue = String(decl.initialValue);
      } else {
        initialValue = String(decl.initialValue);
      }

      return `const ${decl.name} = ref(${initialValue});`;
    }).join("\n");

    return {
      stateRefs: refs + "\n\n",
      stateImports: imports
    };
  }

  private generateDataFetches(data: DataBlock): { dataFetches: string; dataImports: Set<string> } {
    const imports = new Set<string>();
    imports.add("ref");
    imports.add("onMounted");

    const fetches = data.fetches.map((fetch) => {
      const varName = fetch.name;
      const loadingVar = `${varName}Loading`;
      const errorVar = `${varName}Error`;

      return `const ${varName} = ref(null);
const ${loadingVar} = ref(true);
const ${errorVar} = ref(null);

onMounted(async () => {
  try {
    const response = await fetch("${fetch.url}");
    ${varName}.value = await response.json();
  } catch (err) {
    ${errorVar}.value = err;
  } finally {
    ${loadingVar}.value = false;
  }
});`;
    }).join("\n\n");

    return {
      dataFetches: fetches + "\n\n",
      dataImports: imports
    };
  }

  private generateLogicHandlers(logic: LogicBlock): { handlers: string; handlerImports: Set<string> } {
    const imports = new Set<string>();

    const handlers = logic.events.map((event) => {
      const handlerName = `handle${event.name.charAt(0).toUpperCase()}${event.name.slice(1)}`;
      const statements: string[] = [];

      event.steps.forEach((step) => {
        if (step.type === "Navigate") {
          // Vue Router navigation
          statements.push(`// Navigate to ${step.to}`);
          statements.push(`window.location.href = "${step.to}";`);
        } else if (step.type === "Toast") {
          // Simple alert for now (can be replaced with Vue toast library)
          statements.push(`alert("${step.message}");`);
        } else if (step.type === "Call") {
          const method = step.method || "POST";
          statements.push(`await fetch("${step.url}", { method: "${method}" });`);
        }
      });

      return `const ${handlerName} = async () => {
  ${statements.join("\n  ")}
};`;
    }).join("\n\n");

    return {
      handlers: handlers + "\n\n",
      handlerImports: imports
    };
  }
}

/**
 * Create and return a Vue plugin instance
 */
export function createVuePlugin(): CodegenPlugin {
  return new VuePlugin();
}

// packages/codegen-react/src/react-plugin.ts
import type { UIHFile, LayoutBlock, MotionBlock, LogicBlock, StateBlock, DataBlock, Node } from "uih-parser";
import { shadRegistry } from "./registry.js";
import prettier from "prettier";
import type { CodegenPlugin } from "./plugin.js";

/**
 * React code generation plugin with shadcn/ui component support
 */
export class ReactPlugin implements CodegenPlugin {
  readonly name = "react";
  readonly fileExtension = ".tsx";

  async generate(file: UIHFile): Promise<string> {
    // Generate user imports from .uih files and collect imported component names
    const importedComponents = new Set<string>();
    const userImports = file.imports.map((imp) => {
      // Track all imported component names
      imp.names.forEach(name => importedComponents.add(name));

      const importPath = imp.from.replace(/\.uih$/, "");
      if (imp.names.length === 1) {
        return `import ${imp.names[0]} from "${importPath}";`;
      } else {
        return `import { ${imp.names.join(", ")} } from "${importPath}";`;
      }
    }).join("\n");

    const layout = file.blocks.find((b) => b.type === "Layout") as
      | LayoutBlock
      | undefined;
    if (!layout) throw new Error("Layout block required");

    const motion = file.blocks.find((b) => b.type === "Motion") as
      | MotionBlock
      | undefined;

    const logic = file.blocks.find((b) => b.type === "Logic") as
      | LogicBlock
      | undefined;

    const state = file.blocks.find((b) => b.type === "State") as
      | StateBlock
      | undefined;

    const data = file.blocks.find((b) => b.type === "Data") as
      | DataBlock
      | undefined;

    const imports = new Set<string>();
    const jsx = layout.nodes
      .map((n) => {
        const nodeJsx = this.emitNode(n, imports, importedComponents);
        // Wrap expression nodes (Loop, Conditional) in braces at top level
        return this.isExpressionNode(n) ? `{${nodeJsx}}` : nodeJsx;
      })
      .join("\n");
    const motionStyles = motion ? this.generateMotionStyles(motion) : "";
    const { handlers, handlerImports } = logic ? this.generateLogicHandlers(logic) : { handlers: "", handlerImports: new Set<string>() };
    const { stateHooks, stateImports } = state ? this.generateStateHooks(state) : { stateHooks: "", stateImports: new Set<string>() };
    const { dataHooks, dataImports, fetcher } = data ? this.generateDataHooks(data) : { dataHooks: "", dataImports: new Set<string>(), fetcher: "" };

    // Merge all imports
    handlerImports.forEach(imp => imports.add(imp));
    stateImports.forEach(imp => imports.add(imp));
    dataImports.forEach(imp => imports.add(imp));

    const importStr = [...imports].filter(Boolean).join("\n");
    const code = `
${userImports ? userImports + "\n" : ""}${importStr}
${fetcher ? fetcher : ""}
export default function Page() {
${stateHooks ? stateHooks : ""}${dataHooks ? dataHooks : ""}${handlers ? handlers : ""}
  return (
    <>
      ${motionStyles ? `<style dangerouslySetInnerHTML={{ __html: \`${motionStyles}\` }} />` : ""}
      <div className="container mx-auto p-6">
        ${jsx}
      </div>
    </>
  )
}
`;

    // Format with prettier
    const formatted = await prettier.format(code.trim(), {
      parser: "typescript",
      semi: true,
      singleQuote: false,
      trailingComma: "es5",
      printWidth: 80,
    });

    return formatted;
  }

  // Helper: Check if nodes need Fragment wrapper (multiple nodes or no nodes)
  private needsFragment(nodes: Node[]): boolean {
    return nodes.length !== 1;
  }

  // Helper: Check if node is already an expression (Loop or Conditional)
  private isExpressionNode(node: Node): boolean {
    return node.kind === "Loop" || node.kind === "Conditional";
  }

  // Helper: Wrap JSX in Fragment if needed
  private wrapIfNeeded(jsx: string, nodes: Node[]): string {
    if (this.needsFragment(nodes)) {
      return `<>${jsx}</>`;
    }
    // Single node - check if it's already an expression
    if (nodes.length === 1 && this.isExpressionNode(nodes[0])) {
      // Loop and Conditional already produce {...} expressions, no wrapping needed
      return jsx;
    }
    return jsx;
  }

  private emitNode(n: Node, imports: Set<string>, importedComponents: Set<string>): string {
    if (n.kind === "Text") {
      return n.text;
    }

    if (n.kind === "Conditional") {
      // Only wrap expression nodes in braces if there are multiple children
      const shouldWrapExpressions = n.thenNodes.length > 1;
      const thenJsx = n.thenNodes
        .map((node) => {
          const nodeJsx = this.emitNode(node, imports, importedComponents);
          // Wrap expression nodes in braces only when multiple children exist
          return shouldWrapExpressions && this.isExpressionNode(node)
            ? `{${nodeJsx}}`
            : nodeJsx;
        })
        .join("\n");
      const wrappedThen = this.wrapIfNeeded(thenJsx, n.thenNodes);
      const needsParensThen =
        n.thenNodes.length !== 1 || !this.isExpressionNode(n.thenNodes[0]);

      if (n.elseNodes && n.elseNodes.length > 0) {
        const shouldWrapExpressionsElse = n.elseNodes.length > 1;
        const elseJsx = n.elseNodes
          .map((node) => {
            const nodeJsx = this.emitNode(node, imports, importedComponents);
            // Wrap expression nodes in braces only when multiple children exist
            return shouldWrapExpressionsElse && this.isExpressionNode(node)
              ? `{${nodeJsx}}`
              : nodeJsx;
          })
          .join("\n");
        const wrappedElse = this.wrapIfNeeded(elseJsx, n.elseNodes);
        const needsParensElse =
          n.elseNodes.length !== 1 || !this.isExpressionNode(n.elseNodes[0]);

        const thenPart = needsParensThen ? `(${wrappedThen})` : wrappedThen;
        const elsePart = needsParensElse ? `(${wrappedElse})` : wrappedElse;
        // Return without outer braces (parent will add them if needed)
        return `${n.condition} ? ${thenPart} : ${elsePart}`;
      }

      const thenPart = needsParensThen ? `(${wrappedThen})` : wrappedThen;
      // Return without outer braces (parent will add them if needed)
      return `${n.condition} && ${thenPart}`;
    }

    if (n.kind === "Loop") {
      const childrenJsx = n.children
        .map((node) => {
          const nodeJsx = this.emitNode(node, imports, importedComponents);
          // Wrap expression nodes in braces inside Fragment
          return this.isExpressionNode(node) ? `{${nodeJsx}}` : nodeJsx;
        })
        .join("\n");
      // Return as expression without outer braces (parent will add them if needed)
      return `${n.iterableExpr}.map((${n.iteratorVar}) => (<React.Fragment key={${n.iteratorVar}.id || Math.random()}>${childrenJsx}</React.Fragment>))`;
    }

    // Element node - check if it's an imported component first
    if (n.name && importedComponents.has(n.name)) {
      // This is an imported custom component - render it directly
      const children = (n.children || [])
        .map((c) => this.emitNode(c, imports, importedComponents))
        .join("");

      // Build props string
      const propsStr = (n.props || [])
        .map((p) => {
          const value = String(p.value);
          // Check if value is a variable reference (already has braces)
          if (value.startsWith("{") && value.endsWith("}")) {
            return `${p.key}=${value}`;
          }
          // Check if value is a number
          if (!isNaN(Number(value))) {
            return `${p.key}={${value}}`;
          }
          // String literal - add quotes
          return `${p.key}="${value}"`;
        })
        .join(" ");

      if (children) {
        return `<${n.name}${propsStr ? " " + propsStr : ""}>${children}</${n.name}>`;
      } else {
        return `<${n.name}${propsStr ? " " + propsStr : ""} />`;
      }
    }

    // Not an imported component - check shadcn registry
    const reg = (n.name && (shadRegistry as any)[n.name]) || null;
    const propsObj = Object.fromEntries(
      (n.props || []).map((p) => [p.key, String(p.value)])
    );
    const children = (n.children || [])
      .map((c) => this.emitNode(c, imports, importedComponents))
      .join("");
    if (reg?.import) imports.add(reg.import);
    if (reg?.render) return reg.render(propsObj, children);
    // fallback div
    return `<div>${children}</div>`;
  }

  private generateMotionStyles(motion: MotionBlock): string {
    const cssRules = motion.rules.map((rule) => {
      const { selector, event, props } = rule;

      // Convert motion props to CSS properties
      const cssProps: string[] = [];
      const transitions: string[] = [];

      Object.entries(props).forEach(([key, value]) => {
        if (key === "duration") {
          transitions.push(`all ${value}`);
        } else if (key === "scale") {
          cssProps.push(`transform: scale(${value});`);
        } else if (key === "opacity") {
          cssProps.push(`opacity: ${value};`);
        } else if (key === "rotate") {
          cssProps.push(`transform: rotate(${value}deg);`);
        } else if (key === "x") {
          cssProps.push(`transform: translateX(${value}px);`);
        } else if (key === "y") {
          cssProps.push(`transform: translateY(${value}px);`);
        }
      });

      if (transitions.length === 0) {
        transitions.push("all 200ms ease");
      }
      cssProps.push(`transition: ${transitions.join(", ")};`);

      // Generate CSS rule based on event type
      let pseudo = "";
      if (event === "hover") {
        pseudo = ":hover";
      } else if (event === "focus") {
        pseudo = ":focus";
      } else if (event === "active") {
        pseudo = ":active";
      }

      return `${selector}${pseudo} { ${cssProps.join(" ")} }`;
    });

    return cssRules.join("\n");
  }

  private generateLogicHandlers(logic: LogicBlock): { handlers: string; handlerImports: Set<string> } {
    const imports = new Set<string>();
    const handlers = logic.events.map((event) => {
      const handlerName = `handle${event.name.charAt(0).toUpperCase()}${event.name.slice(1)}`;
      const statements: string[] = [];

      event.steps.forEach((step) => {
        if (step.type === "Navigate") {
          // Next.js router navigation
          imports.add(`import { useRouter } from "next/navigation"`);
          statements.push(`router.push("${step.to}");`);
        } else if (step.type === "Toast") {
          // shadcn/ui toast
          imports.add(`import { useToast } from "@/hooks/use-toast"`);
          statements.push(`toast({ title: "${step.message}" });`);
        } else if (step.type === "Call") {
          // API call
          const method = step.method || "POST";
          statements.push(`await fetch("${step.url}", { method: "${method}" });`);
        }
      });

      return `  const ${handlerName} = async () => {
    ${statements.join("\n    ")}
  };`;
    }).join("\n\n");

    // Add hook calls at the start of the component
    let hookCalls = "";
    if (imports.has(`import { useRouter } from "next/navigation"`)) {
      hookCalls += "  const router = useRouter();\n";
    }
    if (imports.has(`import { useToast } from "@/hooks/use-toast"`)) {
      hookCalls += "  const { toast } = useToast();\n";
    }

    return {
      handlers: hookCalls + "\n" + handlers + "\n",
      handlerImports: imports
    };
  }

  private generateStateHooks(state: StateBlock): { stateHooks: string; stateImports: Set<string> } {
    const imports = new Set<string>();
    imports.add(`import { useState } from "react"`);

    const hooks = state.declarations.map((decl) => {
      const varName = decl.name;
      const setterName = `set${varName.charAt(0).toUpperCase()}${varName.slice(1)}`;

      // Format initial value for code generation
      let initialValue: string;
      if (typeof decl.initialValue === "string") {
        initialValue = `"${decl.initialValue}"`;
      } else if (typeof decl.initialValue === "boolean") {
        initialValue = String(decl.initialValue);
      } else {
        initialValue = String(decl.initialValue);
      }

      return `  const [${varName}, ${setterName}] = useState(${initialValue});`;
    }).join("\n");

    return {
      stateHooks: hooks + "\n\n",
      stateImports: imports
    };
  }

  private generateDataHooks(data: DataBlock): { dataHooks: string; dataImports: Set<string>; fetcher: string } {
    const imports = new Set<string>();
    imports.add(`import useSWR from "swr"`);

    // Generate fetcher function
    const fetcher = `\nconst fetcher = (url: string) => fetch(url).then((res) => res.json());\n`;

    const hooks = data.fetches.map((fetch) => {
      const varName = fetch.name;
      const errorVar = `${varName}Error`;
      const loadingVar = `${varName}Loading`;

      return `  const { data: ${varName}, error: ${errorVar}, isLoading: ${loadingVar} } = useSWR("${fetch.url}", fetcher);`;
    }).join("\n");

    return {
      dataHooks: hooks + "\n\n",
      dataImports: imports,
      fetcher
    };
  }
}

/**
 * Create and return a React plugin instance
 */
export function createReactPlugin(): CodegenPlugin {
  return new ReactPlugin();
}
